version: "3.3"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=thxbiso_DS
      - POSTGRES_DB=db
    volumes:
      - ./src:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


